# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_model.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_model.proto',
  package='scanner_ai',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61i_model.proto\x12\nscanner_ai\"\x0b\n\tAIInitReq\"1\n\tAIInitRes\x12$\n\x06result\x18\x01 \x01(\x0e\x32\x14.scanner_ai.AIResult\"\xa2\x01\n\x12\x41IPredictSampleReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x19\n\x11sampling_rate_khz\x18\x02 \x01(\r\x12\x17\n\x0f\x63\x65nter_freq_khz\x18\x03 \x01(\r\x12\x0e\n\x06\x62w_khz\x18\x04 \x01(\r\x12\x12\n\nnum_chunks\x18\x05 \x01(\r\x12\x13\n\x0boverlay_khz\x18\x06 \x01(\r\x12\x13\n\x0bsamples_len\x18\x07 \x01(\r\"F\n\x12\x41IPredictSampleRes\x12\n\n\x02id\x18\x01 \x01(\r\x12$\n\x06result\x18\x02 \x01(\x0e\x32\x14.scanner_ai.AIResult\".\n\x0f\x41ISampleDataReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07samples\x18\x02 \x03(\x02\"W\n\x0f\x41ISampleDataRes\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tlte_freqs\x18\x02 \x03(\x02\x12\x12\n\numts_freqs\x18\x03 \x03(\x02\x12\x11\n\tgsm_freqs\x18\x04 \x03(\x02\"\xb8\x01\n\nAIModelReq\x12)\n\x08init_req\x18\x01 \x01(\x0b\x32\x15.scanner_ai.AIInitReqH\x00\x12<\n\x12predict_sample_req\x18\x02 \x01(\x0b\x32\x1e.scanner_ai.AIPredictSampleReqH\x00\x12\x36\n\x0fsample_data_req\x18\x03 \x01(\x0b\x32\x1b.scanner_ai.AISampleDataReqH\x00\x42\t\n\x07message\"\xb8\x01\n\nAIModelRes\x12)\n\x08init_res\x18\x01 \x01(\x0b\x32\x15.scanner_ai.AIInitResH\x00\x12<\n\x12predict_sample_res\x18\x02 \x01(\x0b\x32\x1e.scanner_ai.AIPredictSampleResH\x00\x12\x36\n\x0fsample_data_res\x18\x03 \x01(\x0b\x32\x1b.scanner_ai.AISampleDataResH\x00\x42\t\n\x07message*J\n\x08\x41IResult\x12!\n\x1d\x41I_RESULT_SUCCESS_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41I_RESULT_ERROR_UNKNOWN\x10\x01\x62\x06proto3'
)

_AIRESULT = _descriptor.EnumDescriptor(
  name='AIResult',
  full_name='scanner_ai.AIResult',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AI_RESULT_SUCCESS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AI_RESULT_ERROR_UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=842,
  serialized_end=916,
)
_sym_db.RegisterEnumDescriptor(_AIRESULT)

AIResult = enum_type_wrapper.EnumTypeWrapper(_AIRESULT)
AI_RESULT_SUCCESS_UNSPECIFIED = 0
AI_RESULT_ERROR_UNKNOWN = 1



_AIINITREQ = _descriptor.Descriptor(
  name='AIInitReq',
  full_name='scanner_ai.AIInitReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=41,
)


_AIINITRES = _descriptor.Descriptor(
  name='AIInitRes',
  full_name='scanner_ai.AIInitRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='scanner_ai.AIInitRes.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=92,
)


_AIPREDICTSAMPLEREQ = _descriptor.Descriptor(
  name='AIPredictSampleReq',
  full_name='scanner_ai.AIPredictSampleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='scanner_ai.AIPredictSampleReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sampling_rate_khz', full_name='scanner_ai.AIPredictSampleReq.sampling_rate_khz', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center_freq_khz', full_name='scanner_ai.AIPredictSampleReq.center_freq_khz', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bw_khz', full_name='scanner_ai.AIPredictSampleReq.bw_khz', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_chunks', full_name='scanner_ai.AIPredictSampleReq.num_chunks', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overlay_khz', full_name='scanner_ai.AIPredictSampleReq.overlay_khz', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples_len', full_name='scanner_ai.AIPredictSampleReq.samples_len', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=257,
)


_AIPREDICTSAMPLERES = _descriptor.Descriptor(
  name='AIPredictSampleRes',
  full_name='scanner_ai.AIPredictSampleRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='scanner_ai.AIPredictSampleRes.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='scanner_ai.AIPredictSampleRes.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=329,
)


_AISAMPLEDATAREQ = _descriptor.Descriptor(
  name='AISampleDataReq',
  full_name='scanner_ai.AISampleDataReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='scanner_ai.AISampleDataReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='scanner_ai.AISampleDataReq.samples', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=377,
)


_AISAMPLEDATARES = _descriptor.Descriptor(
  name='AISampleDataRes',
  full_name='scanner_ai.AISampleDataRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='scanner_ai.AISampleDataRes.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lte_freqs', full_name='scanner_ai.AISampleDataRes.lte_freqs', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='umts_freqs', full_name='scanner_ai.AISampleDataRes.umts_freqs', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gsm_freqs', full_name='scanner_ai.AISampleDataRes.gsm_freqs', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=466,
)


_AIMODELREQ = _descriptor.Descriptor(
  name='AIModelReq',
  full_name='scanner_ai.AIModelReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='init_req', full_name='scanner_ai.AIModelReq.init_req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predict_sample_req', full_name='scanner_ai.AIModelReq.predict_sample_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_data_req', full_name='scanner_ai.AIModelReq.sample_data_req', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='scanner_ai.AIModelReq.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=469,
  serialized_end=653,
)


_AIMODELRES = _descriptor.Descriptor(
  name='AIModelRes',
  full_name='scanner_ai.AIModelRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='init_res', full_name='scanner_ai.AIModelRes.init_res', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predict_sample_res', full_name='scanner_ai.AIModelRes.predict_sample_res', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_data_res', full_name='scanner_ai.AIModelRes.sample_data_res', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='scanner_ai.AIModelRes.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=656,
  serialized_end=840,
)

_AIINITRES.fields_by_name['result'].enum_type = _AIRESULT
_AIPREDICTSAMPLERES.fields_by_name['result'].enum_type = _AIRESULT
_AIMODELREQ.fields_by_name['init_req'].message_type = _AIINITREQ
_AIMODELREQ.fields_by_name['predict_sample_req'].message_type = _AIPREDICTSAMPLEREQ
_AIMODELREQ.fields_by_name['sample_data_req'].message_type = _AISAMPLEDATAREQ
_AIMODELREQ.oneofs_by_name['message'].fields.append(
  _AIMODELREQ.fields_by_name['init_req'])
_AIMODELREQ.fields_by_name['init_req'].containing_oneof = _AIMODELREQ.oneofs_by_name['message']
_AIMODELREQ.oneofs_by_name['message'].fields.append(
  _AIMODELREQ.fields_by_name['predict_sample_req'])
_AIMODELREQ.fields_by_name['predict_sample_req'].containing_oneof = _AIMODELREQ.oneofs_by_name['message']
_AIMODELREQ.oneofs_by_name['message'].fields.append(
  _AIMODELREQ.fields_by_name['sample_data_req'])
_AIMODELREQ.fields_by_name['sample_data_req'].containing_oneof = _AIMODELREQ.oneofs_by_name['message']
_AIMODELRES.fields_by_name['init_res'].message_type = _AIINITRES
_AIMODELRES.fields_by_name['predict_sample_res'].message_type = _AIPREDICTSAMPLERES
_AIMODELRES.fields_by_name['sample_data_res'].message_type = _AISAMPLEDATARES
_AIMODELRES.oneofs_by_name['message'].fields.append(
  _AIMODELRES.fields_by_name['init_res'])
_AIMODELRES.fields_by_name['init_res'].containing_oneof = _AIMODELRES.oneofs_by_name['message']
_AIMODELRES.oneofs_by_name['message'].fields.append(
  _AIMODELRES.fields_by_name['predict_sample_res'])
_AIMODELRES.fields_by_name['predict_sample_res'].containing_oneof = _AIMODELRES.oneofs_by_name['message']
_AIMODELRES.oneofs_by_name['message'].fields.append(
  _AIMODELRES.fields_by_name['sample_data_res'])
_AIMODELRES.fields_by_name['sample_data_res'].containing_oneof = _AIMODELRES.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['AIInitReq'] = _AIINITREQ
DESCRIPTOR.message_types_by_name['AIInitRes'] = _AIINITRES
DESCRIPTOR.message_types_by_name['AIPredictSampleReq'] = _AIPREDICTSAMPLEREQ
DESCRIPTOR.message_types_by_name['AIPredictSampleRes'] = _AIPREDICTSAMPLERES
DESCRIPTOR.message_types_by_name['AISampleDataReq'] = _AISAMPLEDATAREQ
DESCRIPTOR.message_types_by_name['AISampleDataRes'] = _AISAMPLEDATARES
DESCRIPTOR.message_types_by_name['AIModelReq'] = _AIMODELREQ
DESCRIPTOR.message_types_by_name['AIModelRes'] = _AIMODELRES
DESCRIPTOR.enum_types_by_name['AIResult'] = _AIRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AIInitReq = _reflection.GeneratedProtocolMessageType('AIInitReq', (_message.Message,), {
  'DESCRIPTOR' : _AIINITREQ,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIInitReq)
  })
_sym_db.RegisterMessage(AIInitReq)

AIInitRes = _reflection.GeneratedProtocolMessageType('AIInitRes', (_message.Message,), {
  'DESCRIPTOR' : _AIINITRES,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIInitRes)
  })
_sym_db.RegisterMessage(AIInitRes)

AIPredictSampleReq = _reflection.GeneratedProtocolMessageType('AIPredictSampleReq', (_message.Message,), {
  'DESCRIPTOR' : _AIPREDICTSAMPLEREQ,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIPredictSampleReq)
  })
_sym_db.RegisterMessage(AIPredictSampleReq)

AIPredictSampleRes = _reflection.GeneratedProtocolMessageType('AIPredictSampleRes', (_message.Message,), {
  'DESCRIPTOR' : _AIPREDICTSAMPLERES,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIPredictSampleRes)
  })
_sym_db.RegisterMessage(AIPredictSampleRes)

AISampleDataReq = _reflection.GeneratedProtocolMessageType('AISampleDataReq', (_message.Message,), {
  'DESCRIPTOR' : _AISAMPLEDATAREQ,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AISampleDataReq)
  })
_sym_db.RegisterMessage(AISampleDataReq)

AISampleDataRes = _reflection.GeneratedProtocolMessageType('AISampleDataRes', (_message.Message,), {
  'DESCRIPTOR' : _AISAMPLEDATARES,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AISampleDataRes)
  })
_sym_db.RegisterMessage(AISampleDataRes)

AIModelReq = _reflection.GeneratedProtocolMessageType('AIModelReq', (_message.Message,), {
  'DESCRIPTOR' : _AIMODELREQ,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIModelReq)
  })
_sym_db.RegisterMessage(AIModelReq)

AIModelRes = _reflection.GeneratedProtocolMessageType('AIModelRes', (_message.Message,), {
  'DESCRIPTOR' : _AIMODELRES,
  '__module__' : 'ai_model_pb2'
  # @@protoc_insertion_point(class_scope:scanner_ai.AIModelRes)
  })
_sym_db.RegisterMessage(AIModelRes)


# @@protoc_insertion_point(module_scope)
